defaults:
  - model: lcnn
  - metrics: asvspoof
  - datasets: asvspoof_eval
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_

data_root: ${oc.env:ASVSPOOF_ROOT}

inferencer:
  device_tensors: ["features", "labels"]
  device: auto
  save_path: "asvspoof_eval"
  submission_name: "fisolunov.csv"
  from_pretrained: null
  seed: 1
